### ISSUE TITLE
Implementing author-date in-text citations

### ISSUE THREAD

**Issue by zackbatist** [joksas/hugo-simplecite#6]
First off, I want to thank you for creating and maintaining this module. I'm so glad that I found this, especially since the hugo-cite codebase seems to be no longer maintained (last commit was 3 years ago).

That being said, one key limitation of simplecite in the context of my own use case is the lack of author-date citation format. It says in the readme that this will potentially be implemented in the future and I'm wondering if this has progressed at all. I don't really have any experience developing hugo themes and I'm not here to pester you with a feature request -- I'm mainly wondering if this is still in the cards. I'd be happy to lend support by testing and providing user feedback in case anyone decides to take this on.

**Comment by joksas** [comment]
Thank you, I appreciate it!

I'm not actively working on it. But it shouldn't take too much time.

Would you be able to provide example references of an article, a book, a book chapter, a conference paper, and a webpage, and how these would be referenced in text?

**Comment by zackbatist** [comment]
I think that author-date citations are rather uniform across different types of work. It's more about drawing specific values from the data file and arranging them in combination with user input.

As the name "author-date" suggests, the core components are the names of the authors and the year, and may also include a prefix and a suffix.

For single-author works: `(` `FirstAuthorFamilyName` + `Year` `)`
For two-author works: `(` `FirstAuthorFamilyName` + `and` + `SecondAuthorFamilyName` + `Year` `)`
For works with more than two authors: `(` `FirstAuthorFamilyName` `et al.` `Year` `)`

Prefixes and suffixes should be flexible and subject to user inputted values.
Prefixes typically relate the reference to the preceding text, and may include things like "see", "cf.", "i.e.", "e.g.", etc.
Suffixes refer to specific locations in the referenced text, such as page numbers, page ranges, paragraph numbers, figures, tables, etc.

Here are a few examples:

`(Batist 2024)`
`(Batist et al. 2024: 123)`
`(cf. Batist and Batist 2024: para. 56)`

Each citation should be bounded by a set of parentheses. It should also be possible to include several references in the same citation, all bounded by the same set of parentheses, and separated by semicolons.

Here is an example:

`(Batist 2024: 456; Dallas et al. 2023: fig. 7)`

Although a lower priority, and there may be various ways to do it, in cases where multiple works are being referenced in the same citation, there should be an option to specify a prefix for the whole citation, in addition to the ones for specific references.

It might also be nice if the year contains a hyperlink to the full reference in the bibliography, similar to the existing implementation of numerical references. Specifically, just like how clicking the [1] brings you to the corresponding reference in the bibliography, in the situation I'm proposing clicking the year should have the same behaviour. This would make it consistent with common convention in LaTeX.

I don't think much needs to change for the full bibliographic references in order to author-date in-text citations to be implemented. Perhaps the numerical indicators that prefix each reference should be removed.

One other potential complication relates to counting numerous distinct references that have identical sets of authors and years. For instance, if I reference three distinct papers authored by Batist published in 2024, they should be rendered as Batist 2024, Batist 2024a, Batist 2024b. The order of which one is 2024, 2024a or 2024b should derive from the order in which they appear in the text. These modifications to the year should also be reflected in bibliographical references.

Much of this is based on my experience working with the [BibLaTeX](https://ctan.org/pkg/biblatex) LaTeX package. [Here is a handy cheatsheet](https://tug.ctan.org/info/biblatex-cheatsheet/biblatex-cheatsheet.pdf) for illustrative purposes.

I understand that this is not a major priority and though what I wrote above may read like a series of demands, it's intended to be read more like a protocol, hence the directive style. None of this is really urgent, more "nice to have". Also, other people's experience using author-date citations may vary, but I tried to articulate this in a generalizable way.

**Comment by joksas** [comment]
Thank you, this is very useful! Will try to get to it.

**Comment by zackbatist** [comment]
After further consideration I decided to move my project over to [quarto](https://quarto.org/), which is designed explicitly for my use case of academic writing, and which contains substantial citation features already built in. I'm still happy to test this if/when you get around to it, but I'm leaving this comment in case other people who come across this are in a similar situation, and to indicate that this should not be prioritized unless there is substantial interest from others in the community. Sorry if this inconvenienced you in any way.

**Comment by joksas** [comment]
All good!
